Update to moving-flow-SE
HedvigInsurance/embark pull request #492
Opened 2021-05-18 07:59 UTC by zakkjellin

Added access date picker component to the flow. Wasn't able to add the storeKey though, because I don't understand what that is lol

2021-05-18 11:22 UTC, hedvigoscar commented
@zakkjellin `storeKey` is the same as `key` in `<TextAction>`, for example. It's where the input will be stored for use later. 🙂

2021-06-01 07:59 UTC, hugokallstrom approved these changes

2021-06-04 08:15 UTC, hugokallstrom requested changes

2021-06-04 08:15 UTC, hugokallstrom commented on angel-data/moving-flow-SE.json
> +      "text": "<Message>\n  {EMBARK_MOVING_SE_ACCESS_DATE_MESSAGE_1}\n</Message>\n\n<DatePickerAction next=\"[[{EMBARK_MOVING_SE_CONTINUE_BUTTON}->oldHomeInsuredUntil]]\"\n                  storekey=
```suggestion
      "text": "<Message>\n  {EMBARK_MOVING_SE_ACCESS_DATE_MESSAGE_1}\n</Message>\n\n<DatePickerAction next=\"[[{EMBARK_MOVING_SE_CONTINUE_BUTTON}->oldHomeInsuredUntil]]\"\n                  storekey=\"movingDate\"\n                  label=\"{EMBARK_MOVING_SE_ACCESS_DATE_LABEL}\"\n>\n  <Tooltip>\n    <Title>\n      {EMBARK_MOVING_SE_ACCESS_DATE_TOOLTIP_TITLE}\n    </Title>\n    <Description>\n      {EMBARK_MOVING_SE_ACCESS_DATE_TOOLTIP_DESCRIPTION}\n    </Description>\n  </Tooltip>\n</DatePickerAction>",
```

2021-06-04 08:16 UTC, hugokallstrom approved these changes

2021-06-04 08:17 UTC, merged