remove overflow:scroll on desktop
HedvigInsurance/embark pull request #703
Opened 2021-11-09 15:31 UTC by dendoesit

What?

Hide scrollbars on desktop 

Why ?

We have double scrollbars because of overflow: scroll. 

Not sure why we needed overflow: scroll on the passage container as removing this makes the scrollbar show up when needed ( when the page is small and needs to be scrolled ).
Tested it on a couple of flows on different screen sizes. 

Before:

![image](https://user-images.githubusercontent.com/63097139/140953508-d9eccbb3-d4a4-4d43-bfb9-f5c39274f7a6.png)

Now:

![image](https://user-images.githubusercontent.com/63097139/140953636-3f5c773d-8b9a-466b-8847-30b4f3c2395a.png)
![image](https://user-images.githubusercontent.com/63097139/140954049-1f64ecd2-0caf-4957-aec8-a3f80ea05c35.png)

2021-11-09 16:49 UTC, robinandeer commented
Awesome that you are looking into this! Makes a big difference for users 😌

It's surprising that we can solve it without even "overscroll: auto" 😅 I guess you verified that the we don't scroll away the header, right?

2021-11-10 09:44 UTC, guilhermespopolin submitted a review, later dismissed

2021-11-10 15:24 UTC, dendoesit commented
@robinandeer  I guess it's mostly desktop users that are affected by this but still an improvement 🎉 

I'm not sure what you mean by scroll the header away because you could do that before.

2021-11-10 17:02 UTC, robinandeer requested changes
@danpopoutanu what I mean is that the header should be fixed at the top of the page like this:

<img width="574" alt="Screenshot 2021-11-10 at 17 48 34" src="https://user-images.githubusercontent.com/1220232/141158070-8f3c793d-7b83-4cbb-8301-038c796bb8fe.png">

When I try these changes on web-onboarding, I noticed that things simply get cut-off and I can't scroll to see the rest of the content:

<img width="538" alt="Screenshot 2021-11-10 at 17 59 51" src="https://user-images.githubusercontent.com/1220232/141158453-c93ae29f-1d6b-45ce-b2ee-cfa9acc69e2f.png">

I think we have a problem that testing things in Angel doesn't seem to behave the same as on web-onboarding.

I think the solution we are after is `overflow-y: auto`. Can you verify that this works on windows/firefox?

2021-11-11 08:40 UTC, robinandeer commented on src/Components/Passage.tsx
> +  overflow: auto;
Just because we don't intend to scroll in x-axis

```suggestion
  overflow-y: auto;
```

2021-11-11 08:42 UTC, dendoesit commented on src/Components/Passage.tsx
> +  overflow: auto;
was just about to write.
 we have the extra-buildings screen where if you have more buildings on a small screen we need to scroll left or right.

2021-11-11 09:03 UTC, robinandeer commented on src/Components/Passage.tsx
> +  overflow: auto;
Oh that's very annoying... should probably have another solution for that specifically but I will approve for now!

2021-11-11 09:04 UTC, robinandeer approved these changes
Nice change! Let's remember to fix the extra building setup so it can scroll horizontally independently.

2021-11-11 10:16 UTC, dendoesit commented on src/Components/Passage.tsx
> +  overflow: auto;
nevermind. overflow-y seems to work as well. the extra-building already has scroll implemented when there are multiple boxes. 

tested on several flows and seems to work.

2021-11-11 10:31 UTC, robinandeer approved these changes
If this works for extra buildings -- all good!

2021-11-11 11:29 UTC, merged